app:
  name: "nginx"
  image: "ghcr.io/invasor-de-fronteiras/mirim_bot@sha256:f69865b30a71edb7b4856f4ba712cc89af73ba1f00a25ab8ca7c956a68cb9616"
  replicas: 1

config: {}

network:
  expose: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1