app:
  name: "mirim-bot"
  image: "ghcr.io/invasor-de-fronteiras/mirim_bot:sha-c9f7734"
  replicas: 1

config:
  env: mirim-bot-secrets

network:
  expose: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1