app:
  name: "nginx"
  image: "ghcr.io/invasor-de-fronteiras/mirim_bot:sha-e0f6753"
  replicas: 1

config:
  env: /prod/mirim-bot/env

network:
  expose: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1